import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import {auth} from '@/auth';
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
    const session = await auth();
    return (
        <SessionProvider session={session}> 
            <div>
                <Navbar />
                {children}
            </div>
        </SessionProvider>
    );
}
